#' @import stringr
prep_orig_text <- function(orig_text, orig_file, global_eval = TRUE) {

  # Remove lines that call templar::versions()
  start_call <- orig_text %>% str_which("versions\\(")
  end_call <- which(orig_text == "" | orig_text == "```")
  end_call <- min(end_call[end_call > start_call]) - 1

  orig_text <- orig_text[-c(start_call:end_call)]

  # Fix global eval
  where_global <-
    orig_text %>%
    str_which(fixed("opts_chunk$set"))

  if (global_eval & length(where_global) > 0) {

    orig_text[where_global] <- orig_text[where_global] %>%
      str_replace("eval\\s*=\\s*F(ALSE)?", "eval = TRUE")

  }


  # Put a warning at the top about editing the sub-files
  top_alert <- c(glue::glue("# Warning:  File created automatically"),
                 "# Do NOT edit this file directly, as it may be overwritten.")

  end_yaml <- stringr::str_which(orig_text, "---")[2] - 1

  orig_text <- c(orig_text[1:end_yaml], top_alert, orig_text[-c(1:end_yaml)])

  return(orig_text)

}
