#' Function to eliminate all calls to \code{versions()} and setup chunks
#' #' Helper for \code{version()}
#'
#' @param orig_text Text from the original Rmd/qmd
#' @param eval_orig If to execute the code chunks in the document or not
#'
#' @return Pre-processed text containing a cleaned-up Rmd/qmd
#'

prep_orig_text <- function(orig_text, eval_orig = TRUE) {

  # Remove lines that call templar::versions()
  start_call <- orig_text %>% stringr::str_which("versions(_multilingual)?\\(")

  end_call <- which(orig_text == "" | orig_text == "```")
  end_call <- min(end_call[end_call > start_call])

  orig_text <- orig_text[-c((start_call-1):end_call)]

  # Fix global eval
  where_global <-
    orig_text %>%
    stringr::str_which(stringr::fixed("opts_chunk$set"))

  if (eval_orig & length(where_global) > 0) {

    orig_text[where_global] <- orig_text[where_global] %>%
      stringr::str_replace("eval\\s*=\\s*F(ALSE)?", "eval = TRUE")

  }


  # Put a warning at the top about editing the sub-files
  top_alert <- c(glue::glue("# Warning:  File created automatically"),
                 "# Do NOT edit this file directly, as it may be overwritten.")

  end_yaml <- stringr::str_which(orig_text, "---")[2] - 1

  orig_text <- c(orig_text[1:end_yaml], top_alert, orig_text[-c(1:end_yaml)])

  return(orig_text)

}
