#' Knit different versions of a file
#'
#' @export
versions <- function(pull_solutions = TRUE, to_knit = NULL) {

  if (!isTRUE(getOption('knitr.in.progress'))) return()

  orig_file <- knitr::current_input()

  orig_text <- readLines(orig_file)

  # Drop versions() call
  orig_text <- orig_text %>%
    str_subset("versions\\([^\\)]*\\)", negate = TRUE)

  # Put a warning at the top about editing the sub-files
  top_alert <- c(glue("# Warning:  File created automatically from {orig_file}"),
                 "# Do NOT edit this file directly, as it may be overwritten.")

  end_yaml <- str_which(orig_text, "---")[2] - 1

  orig_text <- c(orig_text[1:end_yaml], top_alert, orig_text[-c(1:end_yaml)])

  orig_opts <- knitr::opts_current$get()


  # Pull out chunk label info pertaining to versions

  chunk_info <- get_version_chunks(orig_text)
  sec_info <- get_version_text(orig_text)

  all_info <- full_join(chunk_info, sec_info) %>%
    mutate_all(~replace_na(.,FALSE))


  always_col_names <- c("starts", "ends", "is_versioned")


  # In case we only want to knit a few of the versions

  if (!is.null(to_knit)) {

    all_info <- all_info[, c(always_col_names, to_knit)]

  } else {

    to_knit <- setdiff(names(all_info), always_col_names)

  }

  # Do we want to use version = "solution" to create separate solutions?

  if (pull_solutions) {

    to_knit <- setdiff(to_knit, "solution")

    for (v in to_knit) {

      sol_name <- paste(v, "solution", sep = "-")

      all_info[[sol_name]] <- all_info[[v]] || all_info[["solution"]]

    }

    all_info <- all_info %>%
      select(-solution)

    to_knit <- setdiff(names(all_info), always_col_names)

  }

  lines_to_delete <- c()

  for (v in to_knit) {

    temp = orig_text

    # Remove sections/chunks from other versions

    delete_me <- all_info$is_versioned & !all_info[,v]

    if (any(delete_me)) {

      lines_to_delete <- all_info[delete_me, c("starts", "ends")] %>%
        pmap( ~.x:.y) %>%
        unlist()

    }


    # Remove version labels on text sections

    if (nrow(sec_info) > 0) {

      lines_to_delete <- unique(c(lines_to_delete,
                           sec_info$starts,
                           sec_info$starts + 1,
                           sec_info$ends))

    }

    temp = temp[-lines_to_delete]

    print(temp)

    # later: remove version options from doc

    new_name <- str_remove(orig_file, ".Rmd") %>% paste0("-", v, ".Rmd")

    options(knitr.duplicate.label = 'allow')

    writeLines(temp, new_name)

    rmarkdown::render(new_name, envir = new.env())

  }


  knitr::opts_current$set(orig_opts)

}


get_version_chunks <- function(source_text) {


  chunk_info <- data.frame(

    starts = source_text %>% str_which("```\\{"),
    ends = source_text %>% str_which("```$"),
    is_versioned = source_text %>%
      str_subset("```\\{") %>%
      str_detect("version\\s*=")

  )

  version_opts <- source_text %>%
    str_subset("```\\{") %>%
    str_subset("version\\s*=")

  version_opts_where <- version_opts %>%
    str_extract_all(",\\s*[:alpha:]+\\s*=\\s*") %>%
    map(~str_which(.x, "version"))

  chunk_versions <- version_opts  %>%
    str_split(",\\s*[:alpha:]+\\s*=\\s*") %>%
    map2_chr(version_opts_where, ~.x[[.y+1]]) %>%
    map(~unlist(str_extract_all(.x, '(?<=\\")[:alnum:]+')))

  all_versions <- chunk_versions %>% unlist() %>% unique()


  for (v in all_versions) {

    chunk_info[!chunk_info$is_versioned, v] <- TRUE
    chunk_info[chunk_info$is_versioned, v] <- chunk_versions %>% map_lgl(~any(str_detect(.x, v)))

  }

  return(chunk_info)

}



get_version_text <- function(source_text) {

  secs <- source_text %>% str_which("%%%")

  if (length(secs) == 0) return(NULL)

  sec_info <- data.frame(
    starts = secs[c(TRUE, FALSE)],
    ends = secs[c(FALSE, TRUE)]
  )

  sec_info$is_versioned = str_detect(source_text[sec_info$starts + 1], "version")

  version_opts <- source_text[sec_info$starts + 1] %>%
    str_extract("(?<=version:).*") %>%
    str_split(",") %>%
    map(str_trim)

  all_versions <- version_opts %>% unlist() %>% unique()


  for (v in all_versions) {

    sec_info[!sec_info$is_versioned, v] <- TRUE
    sec_info[sec_info$is_versioned, v] <- version_opts %>% map_lgl(~any(str_detect(.x, v)))

  }

  return(sec_info)

}



